server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATABASE_PASSWORD}
    url: jdbc:mysql://localhost:3306/sanction
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true