server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: fhb-eDh4CDhh6-E2B4DghcFFA55ahGFA
    url: jdbc:mysql://viaduct.proxy.rlwy.net:27353/railway
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true