server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: BhhHaCF1f321GFh1626cFF23-bfFGc6G
    url: jdbc:mysql://viaduct.proxy.rlwy.net:49942/railway
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true