server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Ef-431HGbdgAH4g2B6cgdEF4ehe2Cgb5
    url: jdbc:mysql://viaduct.proxy.rlwy.net:54518/railway
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true